Repository wwt9829/CSEC-380-Project, pull requests merged in 2019-11, with the labels that each got.

#28 Front end complete
  website/flask/Dockerfile
  website/flask/__pycache__/flask.cpython-34.pyc
  website/flask/__pycache__/flask.cpython-36.pyc
  website/flask/app.py
  website/flask/requirements.txt
  website/flask/static/images/delete.png
  website/flask/static/style.css
  website/flask/templates/homepage.html
  website/flask/templates/login.html
  website/flask/templates/wrongpass.html
  website/flask/templates/wronguser.html
Labels: enhancement

#27 Add database, add docker-compose
  server/database_info.sql
  server/db.env
  server/docker-compose.yml
Labels: enhancement

#29 Connect database and add authenticaiton
  Project2.0-R2.docx
  server/Dockerfile
  server/database_info.sql
  server/docker-compose.yml
  server/index.html
  site/app/Dockerfile
  site/app/flask/__pycache__/flask.cpython-34.pyc
  site/app/flask/__pycache__/flask.cpython-36.pyc
  site/app/flask/chaimtube.py
  site/app/flask/requirements.txt
  site/app/flask/static/images/delete.png
  site/app/flask/static/style.css
  site/app/flask/templates/home.html
  site/app/flask/templates/incorrect.html
  site/app/flask/templates/login.html
  site/db/Dockerfile
  site/db/database.sql
  site/db/db.env
  site/docker-compose.yml
  submissions/act1-2/Activity 1 Questions.docx
  submissions/act1-2/Activity 1 Questions.pdf
  submissions/act1-2/Activity 2 Questions.docx
  submissions/act1-2/Activity 2 Questions.pdf
  submissions/act1-2/Group6-Activities1-2.zip
  tests/.coverage
  tests/__pycache__/test_site.cpython-37-pytest-5.1.2.pyc
  website/flask/Dockerfile
  website/flask/app.py
  website/flask/requirements.txt
  website/flask/templates/wrongpass.html
  website/flask/templates/wronguser.html
Labels: enhancement

#35 Add video support to database
  site/db/database.sql
Labels: enhancement

#37 Update database.sql
  site/db/database.sql
Labels: bug

#41 Add video upload functionality
  site/app/Dockerfile
  site/app/flask/chaimtube.py
  site/app/flask/requirements.txt
  site/db/database.sql
Labels: enhancement

#43 Add functionality to view videos
  site/app/flask/chaimtube.py
  site/app/flask/templates/home.html
  site/db/database.sql
  site/docker-compose.yml
Labels: enhancement

#44 Add video deletion functionality
  site/app/flask/chaimtube.py
Labels: enhancement

#46 Add rate limit for login, more generic error message
  site/app/flask/chaimtube.py
  site/app/flask/requirements.txt
Labels: enhancement

#53 Fix tests
  site/app/flask/chaimtube.py
  tests/.cache/v/cache/lastfailed
  tests/__pycache__/act3_test.cpython-27-PYTEST.pyc
  tests/__pycache__/test_act3.cpython-27-PYTEST.pyc
  tests/act3_test.py
  tests/test_act3.py
Labels: bug

#54 Fix session
  site/app/flask/chaimtube.py
  site/docker-compose.yml
  tests/__pycache__/test_act3.cpython-27-PYTEST.pyc
  tests/__pycache__/test_site-up.cpython-27-PYTEST.pyc
Labels: enhancement

#55 Added test video file
  tests/small.mp4
Labels: enhancement

#66 Added test script for activity 4
  tests/test_act4.py
Labels: enhancement

#72 Fix for test_act4.py
  tests/test_act4.py
Labels: bug

#76 Fix for test_act6
  tests/test_act6.py
Labels: enhancement

#79 Add sanitization to prevent XSS
  site/app/flask/chaimtube.py
  tests/__pycache__/test_act3.cpython-27-PYTEST.pyc
  tests/__pycache__/test_act4.cpython-27-PYTEST.pyc
  tests/__pycache__/test_act6.cpython-27-PYTEST.pyc
  tests/__pycache__/test_site-up.cpython-27-PYTEST.pyc
  tests/test_act4.py
Labels: bug, enhancement

#81 Fix for test_act4
  tests/test_act4.py
Labels: enhancement

#83 Update .travis.yml
  .travis.yml
  SQLInjection/app/flask/chaimtube.py
  SQLInjection/docker-compose.yml
  tests/__pycache__/test_act3.cpython-36-pytest-5.3.0.pyc
  tests/__pycache__/test_act4.cpython-27-PYTEST.pyc
  tests/__pycache__/test_act4.cpython-36-pytest-5.3.0.pyc
  tests/__pycache__/test_act5.cpython-27-PYTEST.pyc
  tests/__pycache__/test_act5.cpython-36-pytest-5.3.0.pyc
  tests/__pycache__/test_act6.cpython-36-pytest-5.3.0.pyc
  tests/__pycache__/test_site-up.cpython-36-pytest-5.3.0.pyc
  tests/test_act3.py
  tests/test_act4.py
  tests/test_act5.py
Labels: bug

#85 Update documentation
  README.md
  documentation/act5_BlindANDvOR.mkv
  documentation/act5_BlindOverSleepCrash.mkv
  documentation/act5_BlindSQLi.mkv
  documentation/act5_classicSQLi.mkv
  documentation/act7_CommandInjection.mp4
  documentation/homepage.png
  documentation/login.png
  tests/test_act2.py
Labels: documentation

#86 Update README.md
  README.md
Labels: documentation

#88 Formatted activity answers
  submissions/act3-7_answers.docx
  submissions/act3-7_answers.pdf
Labels: enhancement
